Paginations
ConductionNL/conduction-components pull request #6
Opened 2022-06-13 09:43 UTC by hghanbari

2022-06-14 07:56 UTC, lencodes requested changes
A good first version @hghanbari. I do have some comments.

There's a `.idea` folder added to this pull request, I'm unsure what the files are and I doubt it should be part of this pull request.

2022-06-14 07:56 UTC, lencodes commented on .idea/.gitignore
> +/dataSources.local.xml
I don't think this is supposed to be a part of this pull request, what is this file, how and why was it created?

2022-06-14 07:56 UTC, lencodes commented on src/index.ts
> +import {Paginations} from "./components/denhaag-wrappers/paginations/Paginations"
This was not prettified.

2022-06-14 07:56 UTC, lencodes commented on src/index.ts
> +  Paginations,
It's _Pagination_ and not _PaginationS_.

2022-06-14 07:56 UTC, lencodes commented on src/components/denhaag-wrappers/paginations/Paginations.css
> +}
The styling of this Pagination wrapper is not the same as on the storybook. I think it has to do with this css being (much) too little.

2022-06-14 07:56 UTC, lencodes commented on src/components/denhaag-wrappers/paginations/Paginations.css
> +}
Tip: the best way to find the right css is by searching within their repository and to use that.

2022-06-14 07:56 UTC, lencodes commented on src/components/denhaag-wrappers/paginations/Paginations.tsx
> +/**
The functionality of this Pagination component is much smaller than the one in the Den Haag storybook. Right now, I think we're missing:

- Link highlighting;
- Current page indicator;
- Disabled page indicators;
- Disabled prev / next buttons;
- ... 

For the full functionality you can check the storybook!

2022-06-22 07:30 UTC, hghanbari commented
Dit component werkt nog niet optimaal.
Dit komt doordat de styling van den haag niet werkt.
9:25 AM
@remko48 is in overleg met Den-Haag

2023-01-17 15:22 UTC, closed without merging